#ifdef GET_REGINFO_ENUM
#undef GET_REGINFO_ENUM

#include "LX32GenRegisterInfoEnums.inc"

#endif // GET_REGINFO_ENUM

#ifdef GET_REGINFO_MC_DESC
#undef GET_REGINFO_MC_DESC

#include "LX32GenRegisterInfoMCDesc.inc"

#endif // GET_REGINFO_MC_DESC

#ifdef GET_REGINFO_HEADER
#undef GET_REGINFO_HEADER

#include "LX32GenRegisterInfoHeader.inc"

#endif // GET_REGINFO_HEADER

#ifdef GET_REGINFO_TARGET_DESC
#undef GET_REGINFO_TARGET_DESC

#include "LX32GenRegisterInfoTargetDesc.inc"

#endif // GET_REGINFO_TARGET_DESC

