name: Rust Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install Verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
    
    - name: Build RTL Library
      run: make librust
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: tools/lx32_validator
    
    - name: Build
      run: cargo build --release --verbose
      working-directory: tools/lx32_validator
    
    - name: Run Tests
      run: cargo run --release --verbose
      working-directory: tools/lx32_validator
